[debug] [2022-05-05T10:34:55.833Z] ----------------------------------------------------------------------
[debug] [2022-05-05T10:34:55.836Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2022-05-05T10:34:55.837Z] CLI Version:   10.8.0
[debug] [2022-05-05T10:34:55.837Z] Platform:      linux
[debug] [2022-05-05T10:34:55.837Z] Node Version:  v17.3.0
[debug] [2022-05-05T10:34:55.838Z] Time:          Thu May 05 2022 12:34:55 GMT+0200 (Central European Summer Time)
[debug] [2022-05-05T10:34:55.839Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-05-05T10:34:55.901Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/undefined [none]
[debug] [2022-05-05T10:34:56.355Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/undefined 403
[debug] [2022-05-05T10:34:56.356Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/undefined {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2022-05-05T10:34:56.356Z] HTTP Error: 403, The caller does not have permission
[debug] [2022-05-05T10:34:56.471Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:47:12)
    at RetryOperation._fn (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:286:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.
